# Exercise 6.3: LU decomposition

This exercise invites you to write your own program to solve simultaneous equations using the method of LU decomposition.

a) Starting ,if you wish, with the program for Gaussian elimination in Example 6.1 on page 218, write a Python function that calculates the LU decomposition of a matrix. The calculation is same as that for Gaussian elimination, except that at each step of hte calculation you need to extract the approriate elements of the matrix and assemble them to form the lower diagonal matrix  **L** of Eq(6.32). Test your function by calculating the LU decomposition of the matrix from Eq. (6.2), then multiplying the **L** and **U** you get and verifying that you recover the original matrix once more.

Eq 6.32

$$L = L_0^{-1}L_1^{-1}L_2^{-1}L_3^{-1} = \begin{pmatrix} a_{00} & 0 & 0 & 0\\
                                                         a_{10} & b_{11} & 0 & 0 \\
                                                         a_{20} & b_{21} & c_{22} & 0 \\
                                                         a_{30} & b_{31} & c_{32} & d_{33} \end{pmatrix} $$

In [3]:
import numpy as np

In [27]:
def LU(A_input, v_input):
    
    '''
    Performs an LU decomposition for a given matrix A,
    and returns the solution L, U of Ax = v using LU decomposition 
    '''
    
    A = A_input.copy()
    v = v_input.copy()
    N = len(A)
    
    #initialize L 
    L = np.zeros((N, N), float) 
    L[:, 0] = A[:,0] #column of a_m0's
    
    #Gaussian elimination 
    for m in range(N): 
        # Divide by the diagonal element 
        div = A[m, m]
        A[m,:] /= div 
        v[m] /= div
        
        # Now subtract from the lower rows 
        for i in range(m+1, N):
            mult = A[i,m]
            A[i,:] -= mult*A[m,:]
            v[i] -= mult*v[m]
        
        # Filling L 
        if m < N-1: 
            L[m+1:,m+1] = A[m+1:, m+1]
            
    #Upper triangular matrix, U
    U = A
    
    # Double Backsubstitution 
    # Ly = v
    y = np.empty(N, float)
    for m in range(N-1, -1, -1): 
        y[m] = v[m]
        for i in range(m+1, N):
            y[m] -= L[m, i]*y[i]
        
    # Ux = y
    x = np.empty(N, float)
    for m in range(N-1, -1, -1): 
        x[m] = y[m]
        for i in range(m+1, N):
            x[m] -= U[m, i]*x[i]
    
    # Useful information 
        
    return(L, U, L.dot(U), x)

In [28]:
A = np.array( [[2, 1, 4, 1], 
            [3, 4, -1, -1], 
            [1, -4, 1, 5], 
            [2, -2, 1, 3]], float)
v  = np.array([-4, 3, 9, 7], float)



In [29]:
print(A)
print(v)
LU(A,v)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[-4.  3.  9.  7.]


(array([[  2. ,   0. ,   0. ,   0. ],
        [  3. ,   2.5,   0. ,   0. ],
        [  1. ,  -4.5, -13.6,   0. ],
        [  2. ,  -3. , -11.4,  -1. ]]),
 array([[ 1. ,  0.5,  2. ,  0.5],
        [ 0. ,  1. , -2.8, -1. ],
        [-0. , -0. ,  1. , -0. ],
        [-0. , -0. , -0. ,  1. ]]),
 array([[ 2.,  1.,  4.,  1.],
        [ 3.,  4., -1., -1.],
        [ 1., -4.,  1.,  5.],
        [ 2., -2.,  1.,  3.]]),
 array([ 2., -1., -2.,  1.]))

Double check your result with numpy.linalg.solve()

In [25]:
x = np.linalg.solve(A,v)
x

array([ 2., -1., -2.,  1.])