# Exercise 6.2:

a) Modify the program gausselim.py in Example 6.1 to incorporate partial pivotting ( or you can write you own program from scratch if you prefer). Run your program and demonstrate that it gives the same answers as the original program when applied to Eq. (6.1).

In [1]:
import numpy as np

In [2]:
def gaus_ellim(A, v):
    
    N = len(A)
    print(A)


    for m in range(N):
    
        # First we have to find the row with the largest pivot
        pivot = m
        largest = np.abs(A[m,m])
    
        for i in range(m+1, N):

            if abs(A[i, m]) > largest:
                largest = np.abs(A[i, m])
                pivot = i
    
        # swap the rows
        original_row = [i for i in A[m, :]]
        pivot_row = [i for i in A[pivot,:]]
        A[m, :], A[pivot, :] = pivot_row, original_row
        v[m], v[pivot] = v[pivot], v[m]

        # gaussian elimination
        # divide by the diagonal element we can't use largest because of abs()
        div = A[m, m]
        A[m, :] /= div
        v[m] /= div

        # subtract from lower rows
        for i in range(m+1, N):

            mult = A[i, m]
            A[i, :] -= mult*A[m, :]
            v[i] -= mult*v[m]
    
    
    # back substitution
    x = np.empty(N, float)
    for m in range(N-1, -1, -1):
        x[m] = v[m]

        for i in range(m+1, N):
            x[m] -= A[m, i]*x[i]

    print(x)

In [3]:
A = np.array([[2, 1, 4, 1],
           [3, 4, -1, -1],
           [1, -4, 1, 5],
           [2, -2, 1, 3]], float)

v = np.array([-4, 3, 9, 7], float)

gaus_ellim(A, v)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 2. -1. -2.  1.]
