# Exercise 6.1: A circuit of resistors

Consider the following circuit of resistors:

All the resistors have the same resistance $R$. The power rail at the top is at voltage $V_+ = 5$ V. What are the other four voltages, $V_1$ to $V_4$?

To answer this question we use Ohm's law and the kirchhoff current law, which says that the total net current flow out of (or into) any junction in a circuit must be zero.
Thus for the junction at voltage $V_1$, for instance, we have 

$$\frac{V_1-V_2}{R} + \frac{V_1-V_3}{R} + \frac{V_1-V_4}{R} + \frac{V_1-V_+}{R} = 0, $$

or equivalently

$$ 4V_1 - V_2 -V_3 - V_4 = V_+ $$

a) Write similar equations for the other three junctions with unknown voltages.

Node $V_2$:

$$ \frac{V_2-V_1}{R}+\frac{V_2-V_4}{R}+\frac{V_2-0}{R} = 0$$

$$ -V_1 + 3V_2 - 0V_3- V_4 = 0 $$

Node $V_3$:

$$ \frac{V_3-V_+}{R}+\frac{V_3-V_1}{R}+\frac{V_3-V_4}{R} = 0$$

$$ -V_1 + 0V_2 + 3V_3- V_4 = V_+$$


Node $V_4$:

$$ \frac{V_4-V_3}{R}+\frac{V_4-V_1}{R}+\frac{V_4-V_2}{R}+\frac{V_4-0}{R} = 0$$

$$ 0V_1 - V_2 - V_3 + 4V_4 = 0$$


b) Write a program to solve the four resulting equations using Gaussian elimination and hence find the four voltages (or you an modify a program you already have, such as the program gausselim.py in Example 6.1)

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
def gauss_elim(A, v):
    N = len(A)
    
    for i in range(N):
        div = A[i,i]
        A[i, :] /= div
        v[i] /= div
        
        for j in range(i+1, N):
            mult = A[j, i]
            A[j, :] -= mult*A[i,:]
            v[j] -= mult*v[i]
    
    x = np.empty(N, float)
    for m in range(N-1, -1, -1):
        x[m] = v[m]
        for i in range(m+1, N):
            x[m] -= A[m,i]*x[i]
    
    return A, x,v

In [25]:
A = np.array([[4,-1, -1, -1],
    [-1, 3, 0, -1],
    [-1, 0, 3, -1],
    [0, -1, -1, 4]], float)

v = np.array([5, 0, 5, 0])

In [26]:
gauss_elim(A,v)

(array([[ 1.        , -0.25      , -0.25      , -0.25      ],
        [ 0.        ,  1.        , -0.09090909, -0.45454545],
        [ 0.        ,  0.        ,  1.        , -0.5       ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([1.54545455, 0.18181818, 2.        , 0.        ]),
 array([1, 0, 2, 0]))