# Exercise 6.4:
Write a program to solve the resistor network problem of Exercise 6.1 on page 220 using the function solve from numpy.linalg. If you also did Exercise 6.1, you should check that you get the same answer both times.

In [1]:
import numpy as np

In [2]:
A = np.array([[4,-1, -1, -1],
              [-1, 3, 0, -1],
              [-1, 0, 3, -1],
              [0, -1, -1, 4]], float)

v = np.array([5, 0, 5, 0], float)

In [5]:
# solution from 6.1

def gauss_elim(A, v):
    N = len(A)
    
    for i in range(N):
        div = A[i,i]
        A[i, :] /= div
        v[i] /= div
        
        for j in range(i+1, N):
            mult = A[j, i]
            A[j, :] -= mult*A[i,:]
            v[j] -= mult*v[i]
    
    x = np.empty(N, float)
    for m in range(N-1, -1, -1):
        x[m] = v[m]
        for i in range(m+1, N):
            x[m] -= A[m,i]*x[i]
    
    return A, x

gauss_elim(A,v)

(array([[ 1.        , -0.25      , -0.25      , -0.25      ],
        [ 0.        ,  1.        , -0.09090909, -0.45454545],
        [ 0.        ,  0.        ,  1.        , -0.5       ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([2.5       , 1.16666667, 2.83333333, 1.        ]))

In [6]:
np.linalg.solve(A,v)

array([2.5       , 1.16666667, 2.83333333, 1.        ])